"use client"

import * as React from "react"
import { TrendingUp, Target, Gauge, CheckCircle2, Award, Zap } from "lucide-react"

export function PerformanceMetrics() {
  const metrics = [
    {
      label: "Win Rate (Conviction > 75)",
      value: "78.4%",
      change: "+4.1% vs market benchmark",
      icon: Target,
      note: "Based on 342 tracked signals across 30 days",
    },
    {
      label: "Average Realized R:R",
      value: "2.92x",
      change: "Asymmetric upside",
      icon: TrendingUp,
      note: "Trailing stop preservation model",
    },
    {
      label: "Scanning Latency",
      value: "320ms",
      change: "Real-time RYO engine",
      icon: Zap,
      note: "Sub-second orderbook delta detection",
    },
    {
      label: "Discipline Pass Rate",
      value: "92.6%",
      change: "Strict risk gating",
      icon: Award,
      note: "Invalidations honored without emotional override",
    },
  ]

  const liveFeeds = [
    { name: "Hyperliquid Perps", status: "Active · 12ms", ping: "emerald" },
    { name: "Binance Spot/Futures", status: "Active · 18ms", ping: "emerald" },
    { name: "Bybit Derivatives", status: "Active · 14ms", ping: "emerald" },
    { name: "Solana Raydium / Meteora", status: "Active · 25ms", ping: "emerald" },
  ]

  return (
    <section id="metrics" className="py-24 md:py-32 border-t border-slate-200 bg-white">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-16 md:mb-20">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3.5 py-1 text-xs font-semibold text-emerald-700 mb-4">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span>Verified Alpha Metrics</span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-slate-900 leading-tight">
              Conviction measured by hard data
            </h2>
            <p className="mt-3 text-slate-500 text-base sm:text-lg max-w-xl font-normal">
              Every signal generated by Mekiki is timestamped, tracked, and graded against real market execution.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <span className="text-xs font-semibold text-slate-500">System Status:</span>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-100 text-slate-700 text-xs font-medium border border-slate-200">
              <span className="w-2 h-2 rounded-full bg-emerald-500" />
              All 4 Data Engines Online
            </span>
          </div>
        </div>

        {/* Metrics Cards */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {metrics.map((m, idx) => {
            const Icon = m.icon
            return (
              <div
                key={idx}
                className="rounded-2xl border border-slate-200 p-7 bg-white hover:border-slate-300 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-xs font-semibold text-slate-400">
                      {m.label}
                    </span>
                    <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center text-slate-700">
                      <Icon className="w-4 h-4" />
                    </div>
                  </div>
                  <div className="text-4xl font-extrabold tracking-tight text-slate-900 mb-2">
                    {m.value}
                  </div>
                  <div className="text-xs font-semibold text-emerald-600 mb-4">
                    {m.change}
                  </div>
                </div>
                <div className="text-[12px] text-slate-400 font-normal border-t border-slate-100 pt-3">
                  {m.note}
                </div>
              </div>
            )
          })}
        </div>

        {/* Live Exchange Feed Banner */}
        <div className="rounded-2xl border border-slate-200/90 bg-slate-50/70 p-6 sm:p-8 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-full bg-[#2952FF] flex items-center justify-center text-white shrink-0 shadow-sm">
              <Gauge className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-sm font-bold text-slate-900">
                Live Liquidity Connectivity
              </h4>
              <p className="text-xs text-slate-500 mt-0.5">
                Low-latency WebSocket connections streaming orderbook deltas into the judge engine
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            {liveFeeds.map((feed, i) => (
              <div
                key={i}
                className="inline-flex items-center gap-2 rounded-full bg-white px-3.5 py-1.5 border border-slate-200 text-xs font-medium text-slate-700 shadow-sm"
              >
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                <span>{feed.name}</span>
                <span className="text-[10px] text-slate-400 font-normal">
                  {feed.status.split("·")[1]}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
